### ISSUE TITLE
Sample code

### ISSUE THREAD

**Issue by muuuh** [cryptomator/cryptomator-objc-cryptor#3]
Hello,

thank you for your work on Cryptomator.

Could you please consider sharing the code of the current Cryptomator iOS app or providing some sample code for this library?

I tried to use the library but failed.

    #import <ObjectiveDropboxOfficial/ObjectiveDropboxOfficial.h>
    //#import <SETOCryptomatorCryptor/SETOCryptomatorCryptor.h>
    #import <SETOCryptomatorCryptor/SETOCryptorProvider.h>
    #import <SETOCryptomatorCryptor/SETOCryptor.h>
    #import <SETOCryptomatorCryptor/SETOAsyncCryptor.h>
    #import <SETOCryptomatorCryptor/SETOMasterKey.h>

    DBUserClient *client = [[DBUserClient alloc] initWithAccessToken:@"dropboxToken"];
    [[[client.filesRoutes downloadData:@"/Tresor/masterkey.cryptomator"]
      setResponseBlock:^(DBFILESFileMetadata *result, DBFILESDownloadError *routeError, DBRequestError *networkError, NSData *fileContents) {
          if (result) {
              NSLog(@"%@\n", result);
              NSString *dataStr = [[NSString alloc] initWithData:fileContents encoding:NSUTF8StringEncoding];
              NSLog(@"%@\n", dataStr);

              NSString *password = @"secretCryptomatorPassword";
              SETOMasterKey *masterKey = [[SETOMasterKey alloc] init];
              [masterKey updateFromJSONData:fileContents];

              NSError *masterkeyPasswordError;
              SETOCryptor *cryptor = [SETOCryptorProvider cryptorFromMasterKey:masterKey withPassword:password error:&masterkeyPasswordError];
              if (masterkeyPasswordError) {
                  NSLog(@"%@", masterkeyPasswordError);
              }

              NSString *decryptedFilename = [cryptor decryptFilename:@"...KMQBNSUA4NRU===" insideDirectoryWithId:@"/Tresor/d/ZA/...QT7IB5WEIT"];
              NSLog(@"decryptedFilename: %@", decryptedFilename);
          } else {
              NSLog(@"Error: %@\n%@\n", routeError, networkError);
          }
      }] setProgressBlock:^(int64_t bytesDownloaded, int64_t totalBytesDownloaded, int64_t totalBytesExpectedToDownload) {
          NSLog(@"%lld\n%lld\n%lld\n", bytesDownloaded, totalBytesDownloaded, totalBytesExpectedToDownload);
      }];

**Comment by HeminWon** [comment]
+1

**Comment by overheadhunter** [comment]
```
NSString *decryptedFilename = [cryptor decryptFilename:@"...KMQBNSUA4NRU===" insideDirectoryWithId:@"/Tresor/d/ZA/...QT7IB5WEIT"];
```

for `insideDirectoryWithId` you need to provide the directory id (not the path), which can be found [inside the directory file](https://cryptomator.org/security/architecture/#nameEncryption).

~~@tobihagemann how about adding an example for name and content encryption/decryption to the readme.md?~~ edit: lol ok there are already detailed examples, so the problem is not with the code but rather about the concept of the directory id.

**Comment by tobihagemann** [comment]
It's important to know that each directory has a directory ID. The root directory always has an empty directory ID, so in Obj-C it's `@""`. If you're traversing through folders, it's good to have the directory ID handy (by caching it for example).

Let's look at a simple example: Your file `@"...KMQBNSUA4NRU==="` is inside the root directory.

```objc
NSString *parentDirectoryId = @""; // root directory
NSString *decryptedFilename = [cryptor decryptFilename:@"...KMQBNSUA4NRU===" insideDirectoryWithId:parentDirectoryId];
```

If your file `@"...KMQBNSUA4NRU==="` is inside some other directory, you have to download the directory file of the parent directory first, read its contents to get the directory ID, and then use it as the `parentDirectoryId`.

**Comment by muuuh** [comment]
Thank you for your helpful hint in the right direction.
