### ISSUE TITLE
Swift version

### ISSUE THREAD

**Issue by tcurdt** [cryptomator/cryptomator-objc-cryptor#4]
Is there any reason that would prohibit a port/rewrite in swift?

**Comment by tobihagemann** [comment]
Afaik, it shouldn't be an issue to port/rewrite this library to/in Swift.

But there hasn't been a need for this because Cryptomator for iOS is written in Objective-C. If you are or somebody else is willing to give this a try, we'd be happy to review it.

**Comment by tcurdt** [comment]
If I am going down the cryptomator path I might give it a try.

**Comment by tobihagemann** [comment]
Better late than never but there has been a Swift alternative for quite some time: https://github.com/cryptomator/cryptolib-swift
